package exchange

const (
 BTCUSDT = "BTC/USDT"
 LINKUSDT = "LINK/USDT"
 DOGEUSDT = "DOGE/USDT"
 ORDIUSDT = "ORDI/USDT"
 FETUSDT = "FET/USDT"
 BNBUSDT = "BNB/USDT"
 SOLUSDT = "SOL/USDT"
 CKBUSDT = "CKB/USDT"
 ETHUSDT = "ETH/USDT"
 XRPUSDT = "XRP/USDT"
 AGIXUSDT = "AGIX/USDT"

 USDT = "USDT"
 BTC = "BTC"
 LINK = "LINK"
 DOGE = "DOGE"
 ORDI = "ORDI"
 FET = "FET"
 BNB = "BNB"
 SOL = "SOL"
 CKB = "CKB"
 ETH = "ETH"
 XRP = "XRP"
 AGIX = "AGIX"
)